name: Deploy AWS Fargate container

on:
  workflow_dispatch:
  push:

jobs:
  fargate:
    runs-on: ubuntu-latest
    steps:
    - shell: pwsh
      run: |
        Install-Module -Name AWS.Tools.ECS -Force
